# Generated by Django 5.2.3 on 2025-06-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='raw_text',
            field=models.TextField(blank=True),
        ),
    ]
